# Generated by Django 3.0.3 on 2020-04-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_accountstatus_logindetail_shopkeeperaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQtyType',
            fields=[
                ('qty_type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qty_type_name', models.CharField(max_length=50)),
                ('idx', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_qty_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idx', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('product_qty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ProductQtyType')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.AccountStatus')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
