# Generated by Django 3.0.3 on 2020-03-31 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_accountstatus_logindetail_shopkeeperaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('account_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.PositiveIntegerField()),
                ('verify_email_id', models.BooleanField(default=False)),
                ('verify_phone_no', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.AccountStatus')),
            ],
            options={
                'db_table': 'customer_account',
            },
        ),
    ]
