# Generated by Django 3.0.3 on 2020-03-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('login_detail_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('salt', models.CharField(max_length=10)),
                ('account_type', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'login_detail',
            },
        ),
    ]
