# Generated by Django 3.0.3 on 2020-03-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopKeeperAccount',
            fields=[
                ('account_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.PositiveIntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shop_keeper_account',
            },
        ),
    ]
