# Generated by Django 3.0.3 on 2020-03-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_shopkeeperaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetail',
            name='account_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.ShopKeeperAccount'),
            preserve_default=False,
        ),
    ]
