# Generated by Django 3.0.3 on 2020-03-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200310_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetail',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='shopkeeperaccount',
            name='status_id',
        ),
        migrations.DeleteModel(
            name='AccountStatus',
        ),
        migrations.DeleteModel(
            name='LoginDetail',
        ),
        migrations.DeleteModel(
            name='ShopKeeperAccount',
        ),
    ]
