# Generated by Django 3.0.3 on 2020-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllImage',
            fields=[
                ('image_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=100)),
                ('image_data', models.CharField(max_length=5000)),
                ('parent_type', models.CharField(max_length=50)),
                ('parent_id', models.CharField(max_length=50)),
                ('display_image', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
