# Generated by Django 3.0.3 on 2020-04-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allimage',
            name='idx',
            field=models.IntegerField(default=1),
        ),
    ]
